### ISSUE TITLE
Self Balancing Robot

### ISSUE THREAD

**Issue by Maclain272** [remoteintech/remote-jobs#1058]
it 's this remote can work with self balancing robot without bluetooth?

**Comment by dougaitken** [comment]
I don't understand what you're asking @Maclain272

**Comment by Maclain272** [comment]
Okay ! I am trying to control arduino uno  in my pc for self balancing robot without bluetooth, do you have any idea?

**Comment by dougaitken** [comment]
Wrong place for that type of question @Maclain272 - this is remote as in the "remote from an office" and not "remote control".
