### ISSUE TITLE
Add Quora

### ISSUE THREAD

**Issue by codingknite** [remoteintech/remote-jobs#1139]
![quora](https://user-images.githubusercontent.com/70036189/103438373-b057dc80-4c43-11eb-98d0-0878bf91bec8.png)

Quora announced that starting June 2020 it would be a remote-first company which can also be found on their official website.
Does this qualify it for the list? If so, may I create a pull request for it?

**Comment by dougaitken** [comment]
Hi @codingknite 

Absolutely, please do open a new PR.

Thanks!

**Comment by codingknite** [comment]
Cool @dougaitken Right away!
