### ISSUE TITLE
Better analytics

### ISSUE THREAD

**Issue by dougaitken** [remoteintech/remote-jobs#1152]
I want to add some form of analytics to the site, not Google Analytics as that is too much. 

I used Netlify but for $9 is it not worth it. Althogh the data available is really all I need ([more info in the docs](https://docs.netlify.com/monitor-sites/analytics/#charts)), more than 30 days would help. As this whole project is essentially run by myself, paying ~$100 a year for not useful for that.

The tough point comes with page visits - the front-end site is averaging over 25/30K views and that is outside of Hacktoberfest.

I'd like to look into what options are available to use where I can access minimal data to improve the site. For example, the most visited 404 page is `robots.txt` which doesn't exist so that needs to be sorted #1153 

The option would be to move back to GitHub Pages but again GitHub only has rolling 30-day analytics.

**Comment by 007tom** [comment]
[Segment](https://segment.com)

**Comment by stt106** [comment]
Sorry but what site do you mean? Is this deployed somewhere outside GitHub?

**Comment by pelintang** [comment]
Hallo all ,

**Comment by dougaitken** [comment]
Yes @stt106 the site is built on GitHub but then deployed to Netlify. 

Fathom has been good in this short term so I'm going to close this out for now.
