### ISSUE TITLE
Need help with Hacktoberfest?

### ISSUE THREAD

**Issue by dougaitken** [remoteintech/remote-jobs#1233]
If you need help with Hacktoberfest, comment here and I'll walk you through contributing.

**Comment by sharechiwai** [comment]
@dougaitken , Yes, I need help with Hacktoberfest, could you walk me through please?

**Comment by ANUSHRAVGARG** [comment]
@dougaitken ,Yes ,I need help with Hacktoberfest,could you walk me through this with contribution please??

**Comment by chhavi18387** [comment]
Hey @dougaitken, I would like to contribute. Please walk me through the process.

**Comment by Jyoti-prakash-rout** [comment]
I need help with Hacktoberfest? please help me?

**Comment by agaramudhala** [comment]
Please walk me through the process @dougaitken

**Comment by abdelrazek-alaa** [comment]
yes, I'd like to contribute to your project.

**Comment by dougaitken** [comment]
Apologies, this month hasn't been the best. 

Anyone who wants to contribute, please follow this guide:

- Fork this repository to your own GitHub account
- Make changes either on GitHub.com or clone the repository and make the changes locally
- Commit the changes
- Open a pull request (if you have saved the changes to your repository, then GitHub.com should ask if you want to do this).

As long as the Pull Request is _**created**_ within the next 24 hours, then it'll count towards Hacktoberfest.

Let me know how you get on!

**Comment by ANUSHRAVGARG** [comment]
I really like and thanks for connecting me,i will definitely need your
support and i will give my best this time
