### ISSUE TITLE
Access right to create a new PR in order to add a new company

### ISSUE THREAD

**Issue by titanve** [remoteintech/remote-jobs#1242]
Hello,

How can I get the access right in order to create a PR to add a new company?

Thanks.

**Comment by onepiece123fes** [comment]
What this i don't understand can you help me to find a job please

Le lun. 4 oct. 2021 à 21:45, Rafael Mora ***@***.***> a
écrit :

**Comment by titanve** [comment]
Followed these steps and could create the PR:
https://stackoverflow.com/a/22129144/4008161
