### ISSUE TITLE
HOW front-end works?

### ISSUE THREAD

**Issue by ANUSHRAVGARG** [remoteintech/remote-jobs#1245]
describe the topic to as much as you know about

**Comment by kb-s** [comment]
**front-end ensure that website visitors can easily interact with the page**.

## How ?

let's take an example of github we can see many options in our github front-end page like notification icon, github icon and our profile these all are work of front-end developer, **they are responsible for designing the UI of a mobile app or website**.

**Comment by ifmycodecouldtalk** [comment]
Fundamentally, when we are talking about the web, there is the client and the server. The front-end is what the client sees on the browser when an HTTP request is sent to a web server. The front-end includes the UI/UX design of a website, the browser that the client is using, and front-end frameworks like React and Angular.

**Comment by karteljnr** [comment]
Exactly

**Comment by dougaitken** [comment]
I'm closing this as won't fix purely because this is starting to go off topic.
