### ISSUE TITLE
Add freelancermap.com to companies

### ISSUE THREAD

**Issue by carperez** [remoteintech/remote-jobs#1340]

**Comment by dougaitken** [comment]
Hi @carperez if you think a company should be added, please provide more details for why. I don't see any details about this website to explain who they are and why it should be added.

**Comment by carperez** [comment]
Hi @dougaitken, this is a job board where remote projects are published by different clients all over the world

**Comment by dougaitken** [comment]
Hi @carperez, this doesn't fit the details for my list. The list is specifically companies that hire remotely, not job boards and such. Thanks.
