### ISSUE TITLE
Add Safeguard Global to The List

### ISSUE THREAD

**Issue by garethjmsaunders** [remoteintech/remote-jobs#1341]
I have just started working remotely for Safeguard Global who are almost 100% remote.

I gleaned the 'Company technologies' information from their current developer vacancies. I'm also not entirely sure how many employees they have or across how many countries.

# Safeguard Global

https://www.safeguardglobal.com/ 
Worldwide

# Company blurb
Since 2008, Safeguard Global has helped hundreds of organizations pay and hire workers around the world. Today, with over 900 clients and across 15 global offices, we enable business success through smarter, more efficient payroll, onboarding, time and expense management, and more.

Our centralized global payroll solution gives multinationals comprehensive insights into workforce costs to help make data-driven strategic decisions, and our industry-leading employer of record service, Global Employment Outsourcing, enables expansion into 165+ international markets in as little as two weeks.

# Company size
Over 500

# Remote status
Staff are remote.

# Region
Worldwide

# Company technologies
Golang, JavaScript / TypeScript, Node.js, Python, React, MySQL, PostgreSQL, Oracle

# Office locations
Worldwide

# How to apply
See: https://www.safeguardglobal.com/careers/

**Comment by dougaitken** [comment]
Hello!

Great information and this would be a good addition.

Would you like to make a Pull Request for this yourself? I can help out if needed.

**Comment by garethjmsaunders** [comment]
Hey @dougaitken!

To be honest, I'd rather not have to do this—I've got a ton of other stuff going on just now. I really can't prioritise this just now. Sorry.

**Comment by dougaitken** [comment]
Not a problem at all @garethjmsaunders, thank you for opening the Issue, I'll get it added soon!
