### ISSUE TITLE
Java Developer Job

### ISSUE THREAD

**Issue by WAQAS1214** [remoteintech/remote-jobs#1389]
Rate:$82 hour
• Requirements
o Excellent development, coding and scripting skills ie Python, Ruby, Java, JavaScript, PHP, Bash Shell, and Node.js
o Expert knowledge of REST+JSON, web services, SQL and Swagger
o Experienced in BAU security automation strategies
o Demonstrated creative, critical and independent thinking capabilities and troubleshooting skills
o Strong Communication and Collaboration Skills
o Knowledgeable in Infrastructure Security, Vulnerability Management and Policy Compliance
o Experienced in and understanding of Security Practices, Process Flows and Analysis
o Analytical knowledge
o Software Development Lifecycle and Process Automation

• Nice to have
o Knowledge of the Qualys Private Cloud Platform and its associated modules and the Qualys Web Application API

**Comment by dougaitken** [comment]
Hi @WAQAS1214 

This isn't appropriate for this repository - it isn't an advertising space for specific positions.

**Comment by WAQAS1214** [comment]
Thanks
