### ISSUE TITLE
Add Issue Templates 🛠

### ISSUE THREAD

**Issue by IAmTamal** [remoteintech/remote-jobs#1424]
## What i am suggesting to add ? 

I am suggesting to add **Issue Templates** to the repository, it can be as many categories as needed - primary categories of issues are mostly : `bugs`, `docs`, `general feature` and so on.

## Why to add it ? 

Adding an issue Template allows you to organize the issues made by folks in a much better way.
 - We can know if someone wants to add a site.
 - We can know if someone wants to write a test or maybe fix something in the website
 - Here's a general idea : 
 
![image](https://user-images.githubusercontent.com/72851613/192107388-3b5564d1-4efc-4e05-8fd8-ecb271136a77.png)

## Can i work on it ? 

Yes, i will be glad to help an Opensource project grow more !

**Comment by dougaitken** [comment]
Hey @IAmTamal sounds good. 

Almost all the contributions to this repository are PRs rather than Issues but it might help clearing that up. I have been meaning to rework contributions for some time so this would be a welcome change.

**Comment by IAmTamal** [comment]
@dougaitken , okay i'll work on the issue templates then ! 

- Just tell me what are the type of templates you'd want ?  example : bugs and so on. ..
- The PR template was last updated 14 months ago, i'd be happy if you need any change in that.

**Comment by dougaitken** [comment]
@IAmTamal I'll take the Issues template, I'm going to set it up from the repository settings.

If you're looking to contribute, can I ask you to review tue current PR template and open a discussion for changes there, please? 

I'd like it to be more dynamic and ensure contributors are consciously filling it in related to their changes. For example, many people just tick all the boxes on the list which is incorrect, the first box clearly is about housekeeping and if that's checked, it makes the rest redundant. 

Stretch goal is moving most of that to contributing and then having GitHub Actions run those checks before I need to take action.

**Comment by dougaitken** [comment]
Thanks for your offer here @IAmTamal 

I'm going to close this off and add the basics via the Community Standards - 69975d1
