### ISSUE TITLE
Add non-profit column?

### ISSUE THREAD

**Issue by anselmbradford** [remoteintech/remote-jobs#1427]
Hey, what do you think about adding a column with (Y)/(N) for non-profit status to the listing? Working for a non-profit is important to those with student loans in the US because of https://studentaid.gov/manage-loans/forgiveness-cancellation/public-service#qualifying-employer, so it would be nice to see at a glance which orgs are for-profit, and which are non-profit.

**Comment by dougaitken** [comment]
Interesting concept but not something for this board. Some profiles mention nonprofit I think but this would require a refactor of the company profile. Adding a future maybe for this
