### ISSUE TITLE
Add  virtual Scorlling to the long list or add pagination options to the list.

### ISSUE THREAD

**Issue by RAJEEV2510** [remoteintech/remote-jobs#1434]

**Comment by dougaitken** [comment]
I, unsure how pagination would help as it would increase load times for the viewer, and hijacking scroll isn’t good UX.

added to future maybe though.

**Comment by RAJEEV2510** [comment]
Try Virtual Scrolling its Better options if you do not want add pagination add atleast

**Comment by dougaitken** [comment]
@RAJEEV2510 Can you help me understand this "virtual scrolling" with an example, please?

**Comment by RAJEEV2510** [comment]
@dougaitken Virtual Scrolling Reduce the number the nodes of Ui which will be helpful For consuming less memory.

**Comment by dougaitken** [comment]
I've read up about this, sounds intriguing. If someone wants to have a go at integrating this, I'd be interested.
