### ISSUE TITLE
Simple.com, the bank does not exist anymore....

### ISSUE THREAD

**Issue by JulienMellon** [remoteintech/remote-jobs#1487]
Simple.com is now defunct.

https://www.theverge.com/2021/5/9/22427811/simple-bbva-transition-errors-bank-shutdown

here is the listing in question

https://github.com/remoteintech/remote-jobs/blob/main/company-profiles/simple.md

**Comment by Martinsngene** [comment]
Hello @JulienMellon, please can I work on this issue?
A little more description of the task will help me complete it swiftly.

**Comment by dougaitken** [comment]
Closed via #1488
