### ISSUE TITLE
Need help willing to pay for mentorship or guidance

### ISSUE THREAD

**Issue by thepioneercoder** [remoteintech/remote-jobs#1501]
Hi im an insurance agent as my main career and just started learning code to create a software program to help me simplify my sales process. I'm trying to create an extension program that can overlay on top of the dialer program I use to talk to clients. While also have a voice recognization program that can identify keywords that can dictate the level of intent  to buy or if there just shopping or phrases while in real time having a conversation with the client popping up a rebuttals by text in a screen that overlays my dialer system on my browser
If anybody can help it'll be much appreciated _

**Comment by dougaitken** [comment]
Hey @thepioneercoder, good luck to you furthering your career! 

This repository isn't to see out job help or support like this, but I applaud your eagerness. 

As here won't be the best place for you to get support for this, I'm not sure where best to direct you. 

Maybe posting on Stackoveflow or searching online for similar programs or code?
