### ISSUE TITLE
Data Architect - SnowFlake  100% remote Full-time position

### ISSUE THREAD

**Issue by MariaBeah** [remoteintech/remote-jobs#1597]
WEX is the place that provides exciting opportunities to make a difference because of our familial culture, entrepreneurial spirit, and ambitious attitude. I am currently looking for a Data Architect - SnowFlake  Who brings grit, tenacity, and passion to all that they do. Who looks at every opportunity to improve, invent and innovate a better way forward. Who is a caring collaborator who embraces diversity in pursuit of common goals, and can celebrate each other's successes and have FUN along the way! Who acts with integrity, communicates transparently, and delivers flawlessly. Please reach out for more information! 

Use the link below to access the full job description and apply: [https://wexinc.wd5.myworkdayjobs.com/WEXInc/job/US---Remote/Data-Architect---SnowFlake_R9080](url)

**Comment by dougaitken** [comment]
Hi @MariaBeah this repository isn't for posting job openings. Pleas see the main readme file for details.

**Comment by MariaBeah** [comment]
Hi Dougaitken, thank you for letting me know. Is there a specific way to post jobs on Github?

**Comment by dougaitken** [comment]
GitHub.com as a whole isn't a job board, it helps organise and collaborate on code. Specific job boards might be useful to investigate but I'm afraid I don't know many; `https://remoteok.com` is one I know of, along with standard sites like Indeed
