### ISSUE TITLE
[Question] Where do we upload CVs?

### ISSUE THREAD

**Issue by scheung38** [remoteintech/remote-jobs#1614]
Is this feature available?

**Comment by KieranRobson** [comment]
It is not, this is a place to find remote jobs, not a coaching or job pairing site.

**Comment by dougaitken** [comment]
For clarity - this project is to list companies that hire remotely. As the tag line says:

> A list of semi to fully remote-friendly companies (jobs) in tech.

Some companies may be offering open positions and some may not, this project only lists the companies.
