### ISSUE TITLE
Is a Developer's Location important?

### ISSUE THREAD

**Issue by SurajanShrestha** [remoteintech/remote-jobs#1628]
Hello, I am a Software Engineer currently residing in Kathmandu, Nepal. 
I had a question for you guys. 
Can a developer from Nepal also apply and get a remote job? 
Or do we need to be specifically in Regions like: USA, UK, Canada, Australia, Europe?

**Comment by KieranRobson** [comment]
It may be specific to each company, they may have certain limits. Your best bet would be get in touch with the person hiring for positions
