### ISSUE TITLE
Is (or was) there a native job platform on Github?

### ISSUE THREAD

**Issue by thomasallnice** [remoteintech/remote-jobs#1629]
A friend told me there was a job platform that is part of Github. Have you ever heard about it? If so - what happened? Thanks

**Comment by KieranRobson** [comment]
Hi there

I do not believe this has ever been available. You can link to your website and CV on your [Github Readme](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme)
