### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by annamourasobral** [remoteintech/remote-jobs#1637]
I noticed that has been 10 months since the last merge and a bunch of new PRs so I wonder if the project is still maintained, I would like to contribute by adding the company I work for if affirmative.

**Comment by KieranRobson** [comment]
As a helper, I check it whenever there is a new PR and new issue and can triage, however I do not have merge rights. 

If you make the PR, I am happy to review.

**Comment by KieranRobson** [comment]
@dougaitken may be able to provide further information.
