### ISSUE TITLE
Request: Dark Mode Feature.

### ISSUE THREAD

**Issue by Haris-Mohanty** [remoteintech/remote-jobs#1651]
I'd like to propose the addition of a dark mode feature to enhance the user experience of this fantastic open-source project. Dark mode has become increasingly popular in recent years for its benefits, such as reduced eye strain, improved accessibility in low-light environments, and alignment with modern design preferences.

**Comment by Haris-Mohanty** [comment]
May I add the feature?

**Comment by subhranil002** [comment]
Hey! @dougaitken ... Can you please assign me the task ?

**Comment by shivam-rawat-222** [comment]
please assign me this ..

**Comment by dougaitken** [comment]
Hi all, I'm hopefully going to be changing the theme completely so adding dark mode to this won't be a good contribution.

**Comment by Haris-Mohanty** [comment]
Ok fine
