### ISSUE TITLE
Improve frontend

### ISSUE THREAD

**Issue by Bhanu-code** [remoteintech/remote-jobs#1658]
PLEASE OPEN A NEW DISCUSSION.

[Discussions > New > Ideas](https://github.com/remoteintech/remote-jobs/discussions/new?category=ideas)
Improve frontend appearence of the website and table layout

**Comment by Satyaaam** [comment]
ok,  what kind of apperiance you want for the website, basically what kind of improvement you want

**Comment by JaiminR28** [comment]
Any help with the Updatation with the UI.

**Comment by Bhanu-code** [comment]
thinking to improve the table layout with some hovering and theming.

**Comment by KieranRobson** [comment]
See https://github.com/remoteintech/remote-jobs/issues/1651#issuecomment-1741774789

The front end will be changing soon so this may not be needed.
