### ISSUE TITLE
go to top button

### ISSUE THREAD

**Issue by aditya-stoic-sharma** [remoteintech/remote-jobs#1674]
PLEASE OPEN A NEW DISCUSSION.

[Discussions > New > Ideas](https://github.com/remoteintech/remote-jobs/discussions/new?category=ideas)
so the web page is very long so a go to top button is must for better user experience.
I can make that so please assign me this issue under hacktoberfest

**Comment by AAKASHBANSAL96** [comment]
Also, we can add pagination to this page that will look good and also will increase UX.

**Comment by harshul-2002** [comment]
sir, i can add go to top buttomn please assign this to me

**Comment by ShaikhHeeba07** [comment]
I'm interested in working on this 'go to top' button feature. I believe I can complete this task effectively. Could you please assign this issue to me?

**Comment by haxkd** [comment]
Added PR #1682
