### ISSUE TITLE
Add new optional field for companies that have an existing hiring pool

### ISSUE THREAD

**Issue by ridge-kimani** [remoteintech/remote-jobs#1677]
### Title

 - Create an optional field to add for companies that have a pool of talent already hired

### Description
-  Some companies work by creating a pool of hires that other companies can check out and single-pick from it. For instance, companies like Toptal already have a number of already employed developers but they are part of a developer market.

### Current Behavior
- Currently, it's not possible to add another field that's outside the template.

### Expected Behavior
- A field like  "Talent Pool" would make sense for such inclusions.

**Comment by dougaitken** [comment]
@ridge-kimani that type of employment isn't part of the focus of this project. From what you've explained, this sounds like listing companies folks can apply to and become "Freelancers for hire". This list solely focused on hiring employees directly.
