### ISSUE TITLE
Create navbar for small devices

### ISSUE THREAD

**Issue by techmannih** [remoteintech/remote-jobs#1726]
Hello 
I m creating feature request for create navbar for small devices 
I want to work on this Feature request .....assign me this issue

**Comment by KieranRobson** [comment]
This will be done during the change over of front end.

**Comment by techmannih** [comment]
yes I m frontend developer 
Assign me this one and mention the path of navbar code. I will change it

**Comment by dougaitken** [comment]
Can you elaborate about what you mean by navbar for small devices, please? 

Understanding what you're looking for will help me understand if this is something that will be fixed soon or if further help is needed.

**Comment by TejasChaudhariNdb** [comment]
is this task completed or should I take it?

**Comment by dougaitken** [comment]
I'm going to close this, a new site is in the works and that will have a header nav. I just haven't had the time to dedicate towards it.
