### ISSUE TITLE
Remove Codestunts

### ISSUE THREAD

**Issue by LillyTS** [remoteintech/remote-jobs#1739]
Codestunts | [https://codestunts.com/](https://codestunts.com/)
I tried to enter that website and it doesn't exist

**Comment by asahelcode** [comment]
Assign this to me

**Comment by KieranRobson** [comment]
@asahelcode Feel free to carry this out without being assigned

**Comment by mohammed-anwar404** [comment]
Hey there, I am new to Open source and a first-time contributor on Hacktoberfest. 
I just wanted to know if this issue is still open. If yes, I would like to contribute to this.

**Comment by severinil** [comment]
Opened PR: https://github.com/remoteintech/remote-jobs/pull/1842
