### ISSUE TITLE
compucorp changed name and website to compuco

### ISSUE THREAD

**Issue by LillyTS** [remoteintech/remote-jobs#1740]
[https://www.compucorp.co.uk/](https://www.compucorp.co.uk/) is now [https://www.compuco.io/](https://www.compuco.io/)

**Comment by asahelcode** [comment]
Assign to me

**Comment by dougaitken** [comment]
@LillyTS @asahelcode anyone can contribute a PR to fix this. If changing a company URL please check both the readme and the company profile file. Thanks.
