### ISSUE TITLE
[Bug] 17hats leads to broken careers page

### ISSUE THREAD

**Issue by tedmarov** [remoteintech/remote-jobs#1799]
**Describe the bug**
There is no careers page for 17hats

**To Reproduce**
1. Go to 'https://www.17hats.com/careers'
2. See error

**Expected behavior**
I expected to see the careers page

**Screenshots**
<img width="917" alt="image" src="https://github.com/remoteintech/remote-jobs/assets/68402820/6abb207f-a7f6-463c-affd-4d4ceebffbc4">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Brave
 - Version: 1.62.156

**Comment by dougaitken** [comment]
Looks like they don't have any open roles, if this remains, I'll remove the company.

**Comment by samridhijain27** [comment]
Can I work on this issue ?

**Comment by dougaitken** [comment]
This is still valid - no careers page and nothing about open roles on the site. 
To fix this, open a PR removing the 17hats line in the readme, and also deleting the matching company profile. Submit the PR.

**Comment by lakshmi930** [comment]
@dougaitken Is this issue open for contribution? Can I pick this up?

**Comment by dougaitken** [comment]
yea @lakshmi930 currently this is open for contribution

**Comment by lakshmi930** [comment]
@dougaitken can you please take a look at the PR? I’m hoping to get this closed as part of hacktoberfest this year.
