### ISSUE TITLE
[Bug] AirTreks "How to apply" link does not work correctly

### ISSUE THREAD

**Issue by tedmarov** [remoteintech/remote-jobs#1801]
**Describe the bug**
Clicking on the link leads to a weird page, and could not find a Careers page

**To Reproduce**
1. Go to https://tripplanner.airtreks.com/route?AFFID=AIRTREKS&DST=AIRFARE_MENU
2. See error

**Expected behavior**
I expected to be able to see something close to a Careers page but got nothing

**Screenshots**
<img width="656" alt="image" src="https://github.com/remoteintech/remote-jobs/assets/68402820/ff67d4ea-0dd3-426a-9972-8ed73d08a59d">
<img width="1677" alt="image" src="https://github.com/remoteintech/remote-jobs/assets/68402820/268583f9-a6c4-4cd1-bb4a-d8dc9ca8fcf2">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Brave
 - Version: 1.62.156

**Comment by dougaitken** [comment]
Looks like AirTreks is [owned by BooksnAll](https://www.bootsnall.com/about-us), there is a [Jobs at AirTreks page](https://airtreks.com/about/jobs-at-airtreks/) so the listing could be updated to use `https://airtreks.com/about/jobs-at-airtreks/`
