### ISSUE TITLE
[Bug] Hanno "closed" in 2023

### ISSUE THREAD

**Issue by tedmarov** [remoteintech/remote-jobs#1802]
**Describe the bug**
Webpage opens to a letter saying Hanno is closed.

**To Reproduce**
1. Go to 'https://hanno.co/'
4. Read letter, see error

**Expected behavior**
A page of jobs, or something that says "no jobs available"

**Screenshots**
<img width="934" alt="image" src="https://github.com/remoteintech/remote-jobs/assets/68402820/c14fa3e3-8676-4327-9af9-5b166c55cc72">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Brave
 - Version: v 1.63.162

**Comment by Emmanuel-222** [comment]
I understand the error though 
But I will be willing to take it up if you would explain to me.
