### ISSUE TITLE
Add scroll to "Top Button" with smooth scrolling

### ISSUE THREAD

**Issue by Abhii5496** [remoteintech/remote-jobs#1849]
PLEASE OPEN A NEW DISCUSSION.

[Discussions > New > Ideas](https://github.com/remoteintech/remote-jobs/discussions/new?category=ideas)

A floating button at the bottom-right, with JavaScript toggling its visibility based on scroll, and smooth scrolling for seamless navigation to the top.

**Comment by shubhamkumaar** [comment]
I want to work on this can you assign me?

**Comment by itamim-coder** [comment]
@Ki-er Hi, Can You Assign me?

**Comment by amitrajitbose** [comment]
I can take this up as a part of hacktoberfest. Kindly assign

**Comment by rajesh2150** [comment]
Hey @Ki-er @Abhii5496  Can You Assign me ?. Thank you.

**Comment by Ki-er** [comment]
Hi all,

This is not in the scope of hacktoberfest

Only additions and modifications of company profiles.

**Comment by RachitSahu26** [comment]
@Abhii5496  Hi! Just following up on this PR. Please let me know if any changes are needed.

**Comment by dougaitken** [comment]
I've got two PRs now open for the exact same thing with different implementations. These aren't valid for Hacktoberfest but for these two I'll add `hacktoberfest-accepted` to them since I'm not merging them.
