### ISSUE TITLE
Add Scalac to the list

### ISSUE THREAD

**Issue by zaharidichev** [remoteintech/remote-jobs#309]
[Scalac.io](https://scalac.io/) is a company with a focus on bespoke development utilizing the Lightbend stack. Its fully remote and is a great place to be. Pretty sure, it should be on the list

**Comment by dougaitken** [comment]
HI @zaharidichev, you can open a Pull Request and full out the needed details, I can then review and add to the list 👍

**Comment by abc516** [comment]
Hi @dougaitken , I'd be open to taking this issue.

**Comment by dougaitken** [comment]
This was sorted in #692 but please do review and help with any others @abc516
