### ISSUE TITLE
Feature Request: Add link to jobs page.

### ISSUE THREAD

**Issue by chrisfromthelc** [remoteintech/remote-jobs#352]
Adding a link to each company's jobs/careers/work with us-type page would be a fantastic addition to the resource.

**Comment by dougaitken** [comment]
You mean like is asked for in the [example.md](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md#how-to-apply) ;)

**Comment by dougaitken** [comment]
closing since this is already in place
