### ISSUE TITLE
is there a mobile.app planned / does remote-job will be extendet to an android-app?

### ISSUE THREAD

**Issue by linoman-zz** [remoteintech/remote-jobs#380]
is there a mobile.app planned / does remote-job will be extendet to an android-app?

love to hear from you

**Comment by dougaitken** [comment]
Hi @linoman-zz, not on my roadmap. The front end search which is the next make thing will be responsive but no native apps

**Comment by nylen** [comment]
Closing this one... there are still some improvements to be made for small screens (#465), but https://remoteintech.company is mostly mobile-friendly and this should be all we need here.
