### ISSUE TITLE
Update package-lock.json

### ISSUE THREAD

**Issue by dougaitken** [remoteintech/remote-jobs#384]
Yo @nylen you able to grab this and walk me through a how-to for similar?

https://github.com/remoteintech/remote-jobs/blob/3bbfe49a51f7765b07aaf489580f731196e75cf1/package-lock.json

Cheers!

**Comment by nylen** [comment]
I assume that GitHub is complaining about one of our dependencies or sub-dependencies, but I can't see which one since this feature is limited to repo admins by default:  https://help.github.com/articles/about-security-alerts-for-vulnerable-dependencies/

I usually use this tool to update dependencies:  https://github.com/tjunnone/npm-check-updates

**Comment by dougaitken** [comment]
Yea, for some reason the comment cut off a line: 

"The marked dependency defined in package-lock.json has a known moderate severity security vulnerability in version range < 0.3.9 and should be updated. Review vulnerable dependency"

Hah. I'll try that myself tomorrow or something but I'll probably break it 😂

**Comment by nylen** [comment]
See #387.  Here's what I did:

```
✓ james@xps15 ~/code/remote-jobs $ npm install -g npm-check-updates
/home/james/.nvm/versions/node/v9.3.0/bin/npm-check-updates -> /home/james/.nvm/versions/node/v9.3.0/lib/node_modules/npm-check-updates/bin/npm-check-updates
/home/james/.nvm/versions/node/v9.3.0/bin/ncu -> /home/james/.nvm/versions/node/v9.3.0/lib/node_modules/npm-check-updates/bin/ncu
+ npm-check-updates@2.14.0
updated 10 packages in 19.993s
✓ james@xps15 ~/code/remote-jobs $ ncu
Using /home/james/code/remote-jobs/package.json
[..................] / :
The following dependency is satisfied by its declared version range, but the installed version is behind. You can install the latest version without modifying your package file by using npm update. If you want to update the dependency in your package file anyway, run ncu -a.

 marked  ^0.3.7  →  ^0.3.12 

✓ james@xps15 ~/code/remote-jobs $ ncu -a
Using /home/james/code/remote-jobs/package.json
[..................] - :
 marked  ^0.3.7  →  ^0.3.12 

Upgraded /home/james/code/remote-jobs/package.json

✓ james@xps15 ~/code/remote-jobs $ npm install
npm WARN remote-jobs No repository field.
npm WARN remote-jobs No license field.

updated 1 package in 1.13s
```
