### ISSUE TITLE
Match the domain and style of the list site and the blog

### ISSUE THREAD

**Issue by nylen** [remoteintech/remote-jobs#423]
Currently we have https://remoteintech.github.io/remote-jobs/ and https://remoteintech.company/.  After #420, #421, and #422 are done, we should make these two pieces look and feel the same, with unified navigation, theme, etc.

**Comment by edelstone** [comment]
I think you should just use Jekyll for both the list page and the blog, combine the two, and use `https://remoteintech.company` as your custom URL. This would allow you to retire `https://remoteintech.github.io/remote-jobs` for the most part.

You can then link back to the GitHub project (via a top corner ribbon link, for example) for people that are interested in contributing, but other than that, it's just a seamless webpage experience. I'd be happy to help.

**Comment by nylen** [comment]
Hi @edelstone,

To clarify this issue a bit, we currently have remoteintech.company and the GitHub pages URL.

I would have no problem with putting everything under remoteintech.company, but everything to do with this domain so far has been done by @dougaitken. Right now this part is hosted with WordPress.com, which has some niceties like an easy donation link, but doesn't really allow for much custom development.

So the plan that Doug and I have discussed so far is to make remoteintech.company point to the company listings, and have the blog part (what is now remoteintech.company) move to blog.remoteintech.company.

Ok, now about the site generation part. I think the current repository structure mostly makes sense for maintenance, but to achieve what we want for the site, we are going to need to do a good bit of mixing and recombining of the data from the readme and the individual company profiles. For one example, it should (eventually) be possible to filter the list of companies to those that work with React and employ less than 50 people.

I've already built a lot of the validation and parsing logic needed to make that work, in Node.js. So I'd prefer that we stick with something Node-based for the site generator, to avoid adding another set of dependencies from a different language.

Does that context help any? I know where this thing is at and generally where I've planned to take it next, but that is spread out over a bunch of different issues and conversations.

**Comment by edelstone** [comment]
Totally, that's basically what I had in mind for the URLs. As far as the filtering objectives, I didn't know about those, but it makes sense. Thanks for the response.

**Comment by nylen** [comment]
Happy to have some help with the site generation (#421). Right now there is a script that puts a placeholder page up on Netlify. I've been planning to expand on that, probably just something simple with a couple of templates that get filled in with our data, but I don't have a preference there.

Here is how to get at the data: https://github.com/remoteintech/remote-jobs/issues/88#issuecomment-399857201

**Comment by edelstone** [comment]
I actually don't think I'm qualified for that :(

But I will follow along.

**Comment by nylen** [comment]
@edelstone fyi - I got this working today.  It ended up being a pretty big PR (#460).  If you are curious about how it works, there is an outline [here](https://github.com/remoteintech/remote-jobs/tree/master/site), and feel free to ask any questions about specific parts on the PR.
