### ISSUE TITLE
Add a filter for company size

### ISSUE THREAD

**Issue by nylen** [remoteintech/remote-jobs#463]
(to the table at https://remoteintech.company/)

It would be nice to be able to filter companies based on size, probably using some pre-determined ranges.  We should also be able to look at companies that don't have a known size.

The data for company size will need further cleanup and automated validation before this is possible.

**Comment by dougaitken** [comment]
This was brought up in #474.

Unless you see an easier way of keeping the details up to date _and_ having agreed sizings, I don't think this is viable. 

Closing for now as a `future-maybe` but leaning towards `wontfix`

**Comment by nylen** [comment]
I was thinking we would use ranges based on the data that's already there. But I agree this would be really hard to do well.
