### ISSUE TITLE
Add filters for company technologies

### ISSUE THREAD

**Issue by nylen** [remoteintech/remote-jobs#464]
(to the table at https://remoteintech.company/)

It would be nice to be able to filter companies based on the technologies they use, probably using a list sorted by frequency.  We should also be able to look at companies that don't have a cleanly defined list of technologies.

The data for company technologies will need significant cleanup and automated validation before this is possible.

**Comment by dougaitken** [comment]
I think the search on https://remoteintech.company is enough for now until another overhaul happens. I'm closing this one for now.
