### ISSUE TITLE
False listing for wordtothewise

### ISSUE THREAD

**Issue by wttw** [remoteintech/remote-jobs#469]
Please remove all mention of wordtothewise from your list.

**Comment by wttw** [comment]
Thanks.

No objection to what you're doing in general, but Indian outsourcing spammers are using your list to generate email addresses to send spam to and not being on your list is the most effective way to avoid that B2B spam.

**Comment by nylen** [comment]
That is unfortunate.  How did you find out that this list is the source of the emails?

**Comment by wttw** [comment]
One of the spammers told me:

> Hey Steve,Sorry to upset you  Here is the list of remote friendly companies that had Word To The Wise on it: https://github.com/remoteintech/remote-jobs
> 
> We did use https://hunter.io/ to get your email address to reach out but definitely didn't mean any malicious intent. Enjoy the rest of your week.

The pattern of traffic I've seen recently suggests that this is a broader problem than just a single Indian spammer. (We're an email / anti-abuse company so we track this sort of thing a bit more than most places would).
