### ISSUE TITLE
Add technical overview/contributing document

### ISSUE THREAD

**Issue by nylen** [remoteintech/remote-jobs#482]
It would be a good idea to have a contributing document for developers, since there is a non-trivial amount of code here now, and our main contributing document is oriented towards people who are adding or updating info for their company.

This blog post should be a good start, but it would need to be reformatted a bit:

https://blog.remoteintech.company/2018/09/19/website-updates/

It would also be good to get some feedback from developers who aren't familiar with the project yet to see what should be included there and how it should be organized.

**Comment by nylen** [comment]
There is also already `site/README.md` which I totally forgot about. Probably needs to be linked from more places.

**Comment by ZawadiSumba66** [comment]
Hey, @nylen  is this already an issue? I would like to contribute

**Comment by dougaitken** [comment]
@ZawadiSumba66 nylen isn't involved anymore, it's just me.

If you'd like to contribute, then please open a Pull Request with your thoughts, or elaborate here. 

Important - I would like to move towards another system such as Jekyll so the current technical setup isn't set in stone.

**Comment by owengaspard** [comment]
Hey, I would love to work on this!

**Comment by Jaya-sys** [comment]
Hey i would like to work on this issue can you please assign this issue to me?

**Comment by dougaitken** [comment]
@Jaya-sys Thanks for your interest. Being honest, I'm not assigning this specific Issue to anyone. It will remain open and unassigned until a full contribution is merged which answers this main topic.

If you'd like to contribute, please review this Issue in full and open a Pull Request with your ideas and contributions.

**Comment by dhruvchandak30** [comment]
@dougaitken  Should I add a new item here like `Contribute`

**Comment by jainendra001** [comment]
Hi @dougaitken can I work on this issue, I am a full stack developer from India and currently an undergrad at IIT . So do you mean that I have to first provide the full solution for this issue?

**Comment by dougaitken** [comment]
@dhruvchandak30 @jainendra001 Thanks for the interest but as @KieranRobson said, this may not be appropriate. 

I'm going to lock this Issue for now and return to it later.

**Comment by Dxuian** [comment]
is this still open ?

**Comment by dougaitken** [comment]
Although needed, this is not applicable right now.

**Comment by Cassienicolelair703** [comment]
It's still open

**Comment by dougaitken** [comment]
Closing this as it's been open for 6 years with no movement. When things progress, a new document will be included.
