### ISSUE TITLE
Dramafever has shut down and needs to be removed

### ISSUE THREAD

**Issue by jacob2964** [remoteintech/remote-jobs#488]
Dramafever.com has a notice on their website that they shutdown on October 16. I tried to make a pull request to remove them from the list but am getting a 403 for some reason when I try to push.

**Comment by nylen** [comment]
@jacob2964 you probably tried to push directly to this repo - instead you'll need to **Fork** this repo to your own username, push to your own fork, then come back here and make the pull request using what you pushed to your fork.

In any case thanks for letting us know!
