### ISSUE TITLE
AngularClass company change to Tipe.io?

### ISSUE THREAD

**Issue by Nirvikalpa108** [remoteintech/remote-jobs#499]
Hey, AngularClass is currently on the READMe, but the company seems to have completely changed as the website listed on READMe takes you to https://tipe.io/. They seem to be in beta, so maybe the company has pivoted? Either way there's not much info on the Tipe site to create a profile. Worth deleting AngularClass for now? What do you think?

**Comment by nylen** [comment]
Good catch, and thanks for helping us keep the list up to date!

AngularClass already has a profile that just says "We don't have much information about this company".  Let's leave it this way but rename it to Tipe.io.

**Comment by Nirvikalpa108** [comment]
Nice one, sounds good.
