### ISSUE TITLE
Add Scopic Software

### ISSUE THREAD

**Issue by marinehb** [remoteintech/remote-jobs#518]
[Scopic Software](https://scopicsoftware.com/)

_Company blurb_
Custom solutions for virtually everything. The world’s largest virtual company. We create custom solutions for virtually everything! Our passion is developing visually engaging and interactive solutions, custom made to enhance your business. Over a decade of service and 1000+ projects, developing digital products and user-centric software for a wide range of industries and niches including: Manufacturing, Music and film, Fintech, Food and Fitness, Healthcare and Gaming.

_Company size_
200+ number of Scopic team members.

_Remote status_
We are a fully remote company, with our team member located in 30+ countries.

_Region_
Albania
Argentina
Armenia
Belarus
Brazil
Bulgaria
Chile
Colombia
Croatia
Dominican Republic
Ecuador
Georgia
Kazakhstan
Kosovo
Kyrgyzstan
Macedonia
Moldova
Peru
Philippines
Poland
Portugal
Romania
Russia (but not Crimea)
Serbia
Ukraine
Uzbekistan
Vietnam

_Company technologies_
WEB FRAMEWORKS
We turbocharge our development process with state of the art frameworks such as Yii, Django, Symfony, Spring, Java and Node.js.

RESPONSIVE DESIGN
At Scopic we believe it’s not about the size but what you do with it. With technologies like Bootstrap and LESS, there’s not a screen size we don’t love.

NATIVE/CROSS-PLATFORM SDKS
We’re not tied down by a single platform; we like to play the field. We use Xamarin, AdobeAIR, PhoneGAP and Qt to cater to different operating systems. 

OPENGL, DIRECT3D
We are experts in standard 3D design. We utilize computer vision libraries such as OpenGL, OpenCV and DirectD3.

SQL AND NOSQL DATABASES
Scopic has a foot in both worlds. We use tried and true SQL when the fit is right, but aren’t afraid to delve into newer technologies like Hadoop, MongoDB, Dynamo and other applications for big data.

_How to apply_
https://scopicsoftware.com/careers/

**Comment by nylen** [comment]
@marinehb (or anyone else reading this): the new profile for Scopic Software needs to be converted into a [pull request](https://help.github.com/articles/about-pull-requests/).

Here's an [example](https://github.com/remoteintech/remote-jobs/pull/520) of what these changes look like, and the end result should be formatted like our [example profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md).

**Comment by nylen** [comment]
Added in #532.
