### ISSUE TITLE
standardize on US vs. USA

### ISSUE THREAD

**Issue by chovy** [remoteintech/remote-jobs#523]
I'm trying to use the filter on the site, but some comapnies say "US" and others say "USA"

Can we just make them all use "USA" so its easier to filter on?

**Comment by dougaitken** [comment]
Hey @chovy this is part of #485 which will hopefully help clear up a lot of confusion but updating `US` > `USA` would be a quick fix. 

And Thank you! for using the site. Did you find it useful, how did you find the site? What are your thoughts, I'd love to know!

**Comment by chovy** [comment]
Yes, I am looking to contact remote employers as a recruiter.
