### ISSUE TITLE
make all links open in a new tab

### ISSUE THREAD

**Issue by zevaverbach** [remoteintech/remote-jobs#525]
Would you accept a pull request implementing this?  I'd also add <a href="https://icons8.com/icons/set/external%20link" target="_blank">an icon</a> to each link indicating this functionality.

**Comment by zevaverbach** [comment]
Exactly, `target="_blank"` on every link.

Benefits:

I guess it's just an expectation I have as a user that any link to an
external site will open in a separate tab.

Also, consider the scenario of someone wanting to peruse the sites of a
number of prospective employers -- probably the most common scenario for
users of the site: Will they want to click on a link, look at the
employer's site, then go "back"?  Or will they more likely open a bunch of
tabs by holding down ctrl/command-click?  IMO it'd be a nicer experience to
not have to hold down that key, is all.

Those are the benefits I see.  Please let me know your thoughts, and
whether you want some help writing a bot to make those transformations, eh?

Best,

Zev

**Comment by nylen** [comment]
A lot of people would say "absolutely not" to this.  I think the basic argument is that opening links in a new tab removes choice from users, who generally already know how to open links in new tabs if they want to do this.  Doug, you can ask the folks working on WP core / Gutenberg if you want to know more.

I don't have that strong of an opinion, other than that if we do this:

1. `target="_blank"` by itself is [not sufficient](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/)
2. we need to be careful not to new-tab-ify any links within the same site, or links over to the blog site
3. we need a different style (like an icon) for external links ([example](https://en.wikipedia.org/wiki/Help:External_link_icons))
4. it needs to be done within the existing code that generates the static site.

**Comment by edelstone** [comment]
FWIW, my philosophy on `target=_blank` is to only use it if the user would lose work, or media they've initiated is currently playing.

The other typical reasons for this seem to be mostly a wash; some users would expect the behavior and some wouldn't; some want the back button, some want multiple tabs. Users that like multiple tabs at least have other options to achieve that. Additionally, multiple tabs on mobile is a generally bad experience.

**Comment by nylen** [comment]
> Personally I think there's too much `target=_blank` across the site already.

This is definitely helpful context for this issue.  Especially since I wrote these links that way and then forgot about it.  There are 3 kinds of links that already have `target=_blank` (with the appropriate `rel` attributes, but without icons or other distinguishing styles):

https://github.com/remoteintech/remote-jobs/blob/19d89c09b5f7b168a47b7f7ef40ef2746dfcd21a/site/templates/base.html#L122-L124

https://github.com/remoteintech/remote-jobs/blob/19d89c09b5f7b168a47b7f7ef40ef2746dfcd21a/site/templates/company.html#L9-L17

https://github.com/remoteintech/remote-jobs/blob/19d89c09b5f7b168a47b7f7ef40ef2746dfcd21a/site/templates/company.html#L46-L49

We should definitely make all of these links consistent either way.  Another option would be what MediaWiki appears to do by default, which is to add an icon next to external links but _not_ open them in a new window.

**Comment by dougaitken** [comment]
Thanks, @nylen @edelstone - agreeing with you two on this one.

If we can find a code solution for showing that a link directs to an external site then we should go for that.

**Comment by christyram99** [comment]
Hi @dougaitken , I would like to work on this issue.

**Comment by dougaitken** [comment]
Thanks for offering @christyram99, I'm excited to see what you do.

**Comment by christyram99** [comment]
@dougaitken , As of my understanding, we need to open all external links on a new page and an icon to indicate the link is external.

**Comment by dougaitken** [comment]
Yes, that is the general idea @christyram99

**Comment by christyram99** [comment]
Hi @dougaitken ,

Most of the URLs in our repo are external URLs. I am attaching a sample image of how our site will look like if we add an icon after every external link

![image](https://user-images.githubusercontent.com/25861056/97072557-113cb600-15fe-11eb-9a7b-29a5f61d8824.png)

**Comment by christyram99** [comment]
#999 

Hi @dougaitken , I added the pull request. Please check it once.

**Comment by christyram99** [comment]
Hi @dougaitken , I added #1024 pull request for update missing mailto word in links and spelling mistakes of https protol in urls.

**Comment by christyram99** [comment]
Hi @dougaitken , I think we can close this card.

**Comment by dougaitken** [comment]
Resolved via #1024
