### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by gugaalves** [remoteintech/remote-jobs#528]
I've tested broken links using a Google spreadsheets [custom formula](https://medium.com/@the.benhawy/how-to-use-google-spreadsheets-to-check-for-broken-links-1bb0b35c8525), some links need to be fixed:

- Axelerant
Correct URL: https://www.axelerant.com/careers

- Webikon
Correct URL: https://webikon.eu/ (But I can't see any Jobs page there)

**Comment by dougaitken** [comment]
Cheers Guga, I'll take a look some point to clean them up. I think we've had a link checker in the past but it isn't run regularly.

**Comment by nylen** [comment]
Thanks Guga! Pull requests are definitely welcome to fix any broken links.

Checking for broken links automatically is surprisingly difficult, mostly because it is unreliable.  More information from the first time a contributor tried it:  https://github.com/remoteintech/remote-jobs/pull/372#issuecomment-350569070

**Comment by dougaitken** [comment]
Ah, I knew we'd done something like this before! Maybe I should just set a reminder to do it manually on my local copy like one every few months haha.

**Comment by pedrohyvo** [comment]
@dougaitken you can use this npm package to verify markdown broken links (https://github.com/tcort/markdown-link-check) and maybe you can config on github actions

**Comment by rylim** [comment]
Hi @dougaitken I just ran the [markdown-link-check](https://github.com/tcort/markdown-link-check) on the current copy of the site and there are a LOT of broken links 🙂 , going to submit some PRs on it

**Comment by rylim** [comment]
@dougaitken The first PR is Ready for Review.
