### ISSUE TITLE
Move off Travis CI

### ISSUE THREAD

**Issue by dougaitken** [remoteintech/remote-jobs#541]
There is a lot in the tech news about Travis being bought. 

Thoughts on moving to a new CI @nylen. Is it "easy" (comparatively) and something I can do as a weekend project?

**Comment by nylen** [comment]
> Is it "easy" (comparatively)

Our CI configuration is simple (run `npm run validate && npm test`) so this shouldn't be too hard.

I wouldn't worry about this until / unless we start having problems with Travis though.

**Comment by dougaitken** [comment]
:sigh: I guess this is important now

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
