### ISSUE TITLE
Add cloudapp

### ISSUE THREAD

**Issue by dougaitken** [remoteintech/remote-jobs#616]
Add Cloudapp to the main repository via #607 and https://github.com/j-create/remote-jobs/commit/7d9882793b56d3fa1d0f4bde3dbc87b6451a62bd

**Comment by spencer1573** [comment]
I'd like to take this one.

**Comment by martinwheeler** [comment]
Hey @dougaitken, I'll put my hand up for this. I'll re-use the details added in brackets via #607.

**Comment by martinwheeler** [comment]
I just realised that Cloudapp has already been added in #609 😅 maybe this should be closed @dougaitken?

**Comment by nylen** [comment]
Yes indeed, sorry for the confusion.
