### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by RadValentin** [remoteintech/remote-jobs#619]
Website is not loading for me, checked with https://down.com/ and https://www.uptrends.com/tools/uptime, they both confirm that it's down. 

![Screenshot 2019-10-04 at 14 03 59](https://user-images.githubusercontent.com/3300066/66206261-de9ce400-e6af-11e9-8cb9-ee601b2ceb28.png)

cc: @nylen

**Comment by nylen** [comment]
Not sure what happened, but it's back up now. @dougaitken did anything change recently with the domain or hosting?

**Comment by dougaitken** [comment]
Hmm, could be that I renewed the domain a day late?
