### ISSUE TITLE
Add Xapo

### ISSUE THREAD

**Issue by kcneov** [remoteintech/remote-jobs#623]
Xapo is a fully distributed, financial technology company with more than 250 team members across more than 50 countries worldwide. https://xapo.com/

**Comment by SoldierCorp** [comment]
Hi, can I take this one?

**Comment by SoldierCorp** [comment]
Is this still available?

**Comment by kcneov** [comment]
yes, please add it!

**Comment by SoldierCorp** [comment]
Cool, please assign it to me.

**Comment by kcneov** [comment]
Oops, sorry it's already in progress.

**Comment by SoldierCorp** [comment]
No problem, thank you anyway!

**Comment by MagnaibayarMN** [comment]
@kcneov Sir, could you please review my pull request ? #630

**Comment by dougaitken** [comment]
Hi @SoldierCorp @kcneov there are still many companies needing a full Company Profile added per #639 

@MagnaibayarMN Please do reply on #630 - thanks
