### ISSUE TITLE
Fill in missing information for existing companies

### ISSUE THREAD

**Issue by nylen** [remoteintech/remote-jobs#639]
This repository is getting a lot of activity for Hacktoberfest which is great to see!

One thing we need help with is **filling in missing information for existing companies**.  This needs to be done one by one for each company by looking at their website.

This is a good first task, and if you submit 4 PRs for one company each, then you've already met the requirements for Hacktoberfest!

Here's how:

- Go to https://remoteintech.company/ and find companies that have a :warning: _warning emoji_ next to their name
- Click on the company name to go to the company profile page
- At the bottom of the company profile page, click on the "Edit this page on GitHub" link
- Fill in the profile information using our [example profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) as a template. Generally the more information the better, but at least a bit of info about what the company does and where they accept applicants from is a good idea.
- Commit your changes and submit them as a pull request

In the same pull request, you'll also need to edit the main `README.md` file to remove the warning emoji next to the company's name, and add the company's website and hiring region.

**Comment by vincentdoerig** [comment]
Hello, I can work on [Docker](https://remoteintech.company/docker/) and [Filament Group](https://remoteintech.company/filament-group/).

**Comment by vincentdoerig** [comment]
After some research I found that Filament Group does not have a job listing nor do they seek new employees. Should I create a PR removing the company or should I add it anyways?

**Comment by nylen** [comment]
Hi @vincentdoerig, no need to remove the company I think. It's still a good idea to have a bit of info about what they do, and if they'd like to be removed they can come and ask for that themselves.

You can just say something about what you found in the PR: "No job openings are listed on their website, but there is a contact email" etc.

**Comment by garrowp** [comment]
I can do Mozilla and Khan Academy

**Comment by rahuldkjain** [comment]
@nylen Please review the PR https://github.com/remoteintech/remote-jobs/pull/651

**Comment by arieljimenez** [comment]
@nylen, when you have time, take a look at PR #655

**Comment by Tejaswgupta** [comment]
Does it need any more assignees?
I would be happy to help

**Comment by strawberries73** [comment]
Hello, I am new, can I work on this issue?

**Comment by joquendo** [comment]
Hello, I am working on General Assembly. I will submit a PR when ready.

**Comment by Nyette** [comment]
Is Cards Against Humanity still available? I'd like to work on that one.

**Comment by Nyette** [comment]
Working on Help Scout and Honeybadger.

**Comment by pelmini** [comment]
Hello, I will work on fournova voxmedia.

**Comment by dougaitken** [comment]
When working on an update or new addition, please add one per PR, thanks!

**Comment by NainGalvan** [comment]
Hi I would like to work on BlackPixel but they have been acquired by HyperGiant so I will post about HyperGiant instead.

**Comment by Nyette** [comment]
Haiku Learning is now going by the name, PowerSchool. I will submit a PR, reflecting these changes.

**Comment by lostnco1** [comment]
Ok thanks for letting me know

**Comment by lostnco1** [comment]
@nylen  can I help you out so I can understand the process of creating an issue

**Comment by antinoni** [comment]
Hello! I would like to help out with the info for Koding

**Comment by antinoni** [comment]
Hello, I wanted to help out with Koding but couldn't get sufficient info, so I will help with Mozilla instead.

**Comment by ZInAye19** [comment]
Hello, I'd like to work on BuySellAds.

**Comment by dougaitken** [comment]
Hey @ZInAye19 - can you look for another company or two further down the list, I think they is another PR open for that one.

**Comment by fernandakawasaki** [comment]
Hi I would like to work on Enjoei.

**Comment by fernandakawasaki** [comment]
I'd like to work on Focusnetworks, too

**Comment by ngutierrez31** [comment]
I'd like to work on Marketade and Open Craft!

**Comment by antinoni** [comment]
Hello! I'm working on Test Double, Scrapinghub and Vox Media!

**Comment by danishirfannn** [comment]
Hi! I'd like to work on Compose!

**Comment by dougaitken** [comment]
Hey @danishirfannn - need to pick another - that already has about 3 PRs I need to sort out. Can you either pick one from the Issues list of start half way down the list, please?

**Comment by danishirfannn** [comment]
@dougaitken Hi. Sure thing. Can I work on Fire Engine Red?

**Comment by danishirfannn** [comment]
Scopic Software is missing Office Location info. Can I add that?

**Comment by danishirfannn** [comment]
I am new to open source. Kindly tell me if I have to be assigned an issue before making a pull request?

**Comment by dougaitken** [comment]
You can create a PR without an linked issue @danishirfannn 

Please feel free to add whatever is needed - one company per pull request please.

**Comment by danishirfannn** [comment]
@dougaitken Thank you!

**Comment by maxerbox** [comment]
#1006 is related to hacktoberfest

**Comment by Giyan17** [comment]
Hello I can work on [UpTrending](https://remoteintech.company/uptrending/)

**Comment by JiriJAdam** [comment]
Hello! Can I work on this?

**Comment by marychew97** [comment]
Hi, I would like to work on Salesforce :)

**Comment by Giyan17** [comment]
@dougaitken can you review #1028

**Comment by Caitlin-Fotheringham** [comment]
I have submitted a PR for Particular Software (to try and avoid duplicates)

**Comment by ZInAye19** [comment]
Hey, I'd like to work on IPS group and LicolnLoop

**Comment by marychew97** [comment]
Hi again, I would like to work on LivingSocial, Keen IO and Safari Books Online :)

**Comment by dougaitken** [comment]
No need to comment here when working on a PR but please make sure there are no open PRs for the company you're editing/adding.

**Comment by dougaitken** [comment]
Hi @Dahbaeraychy sorry for the delay, I've had a few things on personally. I see you have closed your Pull Requests - is there any reason for that?

**Comment by pedaars** [comment]
Hi, @dougaitken. Are you accepting new companies the company I work for is remote first but missing from your list ?

**Comment by dougaitken** [comment]
Absolutely @pedaars, please do open a Pull Request with a new entry.

**Comment by dougaitken** [comment]
I'm going to close this off for now. I'll add details for contributions to either the Wiki or expand on the contributing file.
