### ISSUE TITLE
Submit the list to the Awesome lists

### ISSUE THREAD

**Issue by hkdobrev** [remoteintech/remote-jobs#70]
You can submit this list to the [Awesome collection of Awesome lists](https://github.com/sindresorhus/awesome). The contribution guidelines require at least 2 weeks wait time for the list to mature.

There's also another such list there already - https://github.com/lukasz-madon/awesome-remote-job.

**Comment by cmtonkinson** [comment]
Nice find @hkdobrev. https://github.com/lukasz-madon/awesome-remote-job isn't a direct duplicate (it's a list of resources, not jobs), but could be incorporated somehow, and is absolutely related.

**Comment by hkdobrev** [comment]
@cmtonkinson Yes, it is not a duplicate, it contains both resources and some remote companies.

**Comment by dougaitken** [comment]
I've open an Issue to discuss this on lukasz-madon/awesome-remote-job/issues/395
