### ISSUE TITLE
It's a hard job to find a job... So...

### ISSUE THREAD

**Issue by danielramosbh74** [remoteintech/remote-jobs#764]
I just I'd like to share **an idea or suggestion** here...

Maybe you, @ksahin, or someonelse can find the idea good and can colaborate to improve it, **merging it on this project** or not...

See more details here:
https://danielramosbh74.github.io/easy-like-this/

Thanks

**Comment by nylen** [comment]
Hi @danielramosbh74, usually the hardest part of making a new service like this is making sure that companies (who would hire contractors) know about it. What's your plan for this?

**Comment by danielramosbh74** [comment]
> Hi @danielramosbh74, usually the hardest part of making a new service like this is making sure that companies (who would hire contractors) know about it. What's your plan for this?

Hi @nylen, yes... I agree with you...

Unfotunately I don't have a plan yet... but we could make it together if you want. One idea is to search for litle companies or better, investors, sponsors, here at Github to increase this project step by step, including creating this first version of the master plan.

I'm not a good vendor... and it's as harder to sell ideas than material things... but, this is one of the most important obstacle to win. I'm good to sistemize, organize and resume procedures, and do believe that simple things work better. See Google for example: just one search box.... and the fantastic algorithm is behind the cenes. 

That's why I believe it's possible to make an efficient and easy marketplace for jobs, testing people in practice. Whatever in what we're working, things must be good for all people involved.

**Comment by nylen** [comment]
I like the idea, but I think you should focus on promoting your service to companies first, so that you have some available jobs.

I think helping with that promotion directly is a bit outside of the goal of this project, we are just providing an index of companies which hire remotely.
