### ISSUE TITLE
NOT AN ISSUE!!!

### ISSUE THREAD

**Issue by myFree** [remoteintech/remote-jobs#771]
Just wanted to say thanks for creating and maintaining this list; its a fantastic resource!!! Much appreciated.

No issue :) Feel free to close

**Comment by dougaitken** [comment]
You’re welcome @myFree - we’re you able to change job due to a company you found on the list? 
I really appreciate any feedback and positive comments like this are wonderful. 

cc @nylen

**Comment by myFree** [comment]
Not quite a happy ending just yet; but I'm only up to `e`s on the list; and finding a lot of interesting companies along the way. So it has been very -very useful
