### ISSUE TITLE
Fixing Travis

### ISSUE THREAD

**Issue by nylen** [remoteintech/remote-jobs#781]
@dougaitken it looks like Travis stopped running a couple of weeks ago, not really sure exactly why but it might be related to travis-ci.org switching over to travis-ci.com. This didn't really break anything too badly but you should have an email to add access to Travis so that PRs can have green checkmarks again.

**Comment by nylen** [comment]
looks like I touched something and it started working again.. not really sure what happened there but ok.

Doug if you see the email from Travis come in it's probably still a good idea to accept that so we can get it fully set up.

**Comment by dougaitken** [comment]
Yes, shits broken.

I keep forgetting I have a different primary email on this. I just approved Travis but it looks like a different app than this one? https://github.com/marketplace/travis-ci/

**Comment by dougaitken** [comment]
Travis is no longer used, we moved to GitHub Actions in #1132
