### ISSUE TITLE
Fixing region of 1Password

### ISSUE THREAD

**Issue by goleedev** [remoteintech/remote-jobs#788]
It looks like 1Password only has remote jobs within the US or Canada not worldwide

**Comment by nylen** [comment]
Would probably be good to check with the person who originally wrote that there are people in Europe and New Zealand - I think they were a 1password employee.

**Comment by KieranRobson** [comment]
With the merge of https://github.com/remoteintech/remote-jobs/commit/209a1fa6e35086dee267b42d459afbf3cc3abdf2, Id say this issue could be closed!

**Comment by dougaitken** [comment]
Their [jobs page](https://jobs.lever.co/1password) includes a single job for Netherlands but I’m happy with the current setup. Thanks for the housekeeping @KieranRobson
