### ISSUE TITLE
String. Of  a mess

### ISSUE THREAD

**Issue by lostnco1** [remoteintech/remote-jobs#858]
Sorry  I  didn't realize that I had created such a mess

**Comment by lostnco1** [comment]
What can I do to contribute to my mistake and also find out how it all happened

**Comment by dougaitken** [comment]
Hey @lostnco1  - it looks like you might have subscribed to all updates so this is why you end up commenting on "random" Issues and Pull Requests. I'm not sure how this is happening.

Are you looking for help on how to contribute to this list for Hacktoberfest?

**Comment by dougaitken** [comment]
@lostnco1 Let's keep the conversation here - you are commenting on different Issues so make sure you're in the right conversation rather than mentioning people in different pull requests

**Comment by lostnco1** [comment]
@dougaitken Well just to contribute in general im usallay on android when trying to do anything here, I am trying to fix what I need to after pguess i sent out all of this from my computer but i just want to make sure that im entering things in the correct place before sending anything out

**Comment by lostnco1** [comment]
@dougaitken  Yea Im using windows now and can see it much better, do you know how i would use a open source license for verifying the volume license for microsoft access

**Comment by dougaitken** [comment]
> do you know how i would use a open source license for verifying the volume license for microsoft access

Different "license" terminology. This has nothing related to Microsoft Access or anything. 

More details of coding licenses can be found here - https://choosealicense.com/

**Comment by lostnco1** [comment]
@dougaitken  ok I see what your saying
